name: Fix signing key
on: workflow_dispatch
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Copy signing key
        env:
          GH_TOKEN: ${{ secrets.COPY_PAT }}
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
        run: |
          printf "%s" "$ANDROID_SIGNING_KEY" | gh secret set ANDROID_SIGNING_KEY --repo antinvestor/service-chat
          echo "Done"